# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mvn dependency:go-offline

      - run: mvn integration-test
      - run: mvn package

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_artifacts:
          name: "Saving Test report"
          path: target/surefire-reports/
          destination: report-test/

      - store_artifacts:
          name: "Saving Jacoco report"
          path: target/site/jacoco/
          destination: report-codecoverage/

      - run: mkdir jar_files && cp target/*.jar jar_files/
      - store_artifacts:
          name: "Saving JAR files"
          path: jar_files
          destination: jar-files/


